"""The art, as code: the Torpedo Tube's icon, the torpedo's model and texture, the fit-out screen,
the recipes and tags this protocol ships, and the box submarine the gametests and the booth dive,
with the test upgrades and the tank they dive in; and the torpedo's launch, cut from a recording.

Run from the repository root:

    uv run --no-project python devtools/art/build.py
    uv run --no-project --with numpy python devtools/art/build.py sounds

Everything it writes is committed; this script is the source of truth for those files. All
original work. Copyright 2026 Rusty Shackleford and nfx. SPDX-License-Identifier: AGPL-3.0-or-later.
"""
from __future__ import annotations

import json
import struct
import sys
import zlib
from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]
MAIN_ASSETS = ROOT / "src/main/resources/assets/submersibles"
MAIN_DATA = ROOT / "src/main/resources/data/submersibles"
TEST = "submersibles_gametest"
TEST_ASSETS = ROOT / "src/gametest/resources/assets" / TEST
TEST_DATA = ROOT / "src/gametest/resources/data" / TEST
TEST_MINECRAFT = ROOT / "src/gametest/resources/data/minecraft"
TEST_TAGS = ROOT / "src/gametest/resources/data/submersibles/tags/item"
STRUCTURES = ROOT / "devtools/gameteststructures"


# ---------------------------------------------------------------- PNG writing

def write_png(path: Path, width: int, height: int, pixels) -> None:
    """pixels: rows of (r, g, b, a) tuples, top row first."""
    raw = b"".join(b"\x00" + b"".join(bytes(p) for p in row) for row in pixels)

    def chunk(kind: bytes, data: bytes) -> bytes:
        return (struct.pack(">I", len(data)) + kind + data
                + struct.pack(">I", zlib.crc32(kind + data) & 0xFFFFFFFF))

    png = (b"\x89PNG\r\n\x1a\n"
           + chunk(b"IHDR", struct.pack(">IIBBBBB", width, height, 8, 6, 0, 0, 0))
           + chunk(b"IDAT", zlib.compress(raw, 9))
           + chunk(b"IEND", b""))
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_bytes(png)


class Noise:
    """A deterministic grain so flat colours read as material, not plastic."""

    def __init__(self, seed: int) -> None:
        self.state = seed & 0xFFFFFFFF

    def next(self) -> float:
        self.state = (1664525 * self.state + 1013904223) & 0xFFFFFFFF
        return self.state / 0xFFFFFFFF


def shade(rgb, delta):
    return tuple(max(0, min(255, c + delta)) for c in rgb)


def write_json(path: Path, data) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(json.dumps(data, indent=2) + "\n")


def canvas(w: int, h: int, fill=(0, 0, 0, 0)):
    return [[fill for _ in range(w)] for _ in range(h)]


# ------------------------------------------------------- the box submarine's atlas

# A 4 x 4 grid of 16-pixel swatches; a face takes one swatch whole, inset so no coordinate sits on
# a swatch's edge (Vanilla Wheels' rule: the cutout shader drops a face that samples the atlas's
# empty padding).
CELLS = {"body": (0, 0), "trim": (1, 0), "glass": (2, 0), "lamp": (3, 0),
         "prop": (0, 1), "metal": (1, 1), "hatch": (2, 1)}
COLOURS = {"body": (205, 205, 205), "trim": (60, 64, 70), "glass": (150, 200, 230), "lamp": (250, 240, 200),
           "prop": (176, 140, 60), "metal": (130, 136, 146), "hatch": (90, 96, 104)}


def atlas():
    noise = Noise(0x5B5B)
    px = canvas(64, 64)
    for name, (cx, cy) in CELLS.items():
        base = COLOURS[name]
        alpha = 160 if name == "glass" else 255
        for y in range(16):
            for x in range(16):
                px[cy * 16 + y][cx * 16 + x] = (*shade(base, int((noise.next() - 0.5) * 16)), alpha)
    return px


class ObjWriter:
    def __init__(self, what: str) -> None:
        self.lines = [f"# generated by devtools/art/build.py: {what}"]
        self.v = 0
        self.vt = 0

    def box(self, material, group, x0, y0, z0, x1, y1, z1):
        """A closed box from (x0,y0,z0) to (x1,y1,z1), six quads on one swatch, wound outward."""
        cx, cy = CELLS[material]
        inset = 0.02
        u0, v0 = cx / 4 + inset / 4, 1 - (cy + 1) / 4 + inset / 4
        u1, v1 = (cx + 1) / 4 - inset / 4, 1 - cy / 4 - inset / 4
        corners = [(x0, y0, z0), (x1, y0, z0), (x1, y1, z0), (x0, y1, z0), (x0, y0, z1), (x1, y0, z1), (x1, y1, z1), (x0, y1, z1)]
        for c in corners:
            self.lines.append("v %.3f %.3f %.3f" % c)
        for (u, vv) in ((u0, v0), (u1, v0), (u1, v1), (u0, v1)):
            self.lines.append("vt %.4f %.4f" % (u, vv))
        base_v = self.v
        base_t = self.vt
        self.lines.append(f"usemtl {material}")
        self.lines.append(f"g {group}")
        faces = [(1, 4, 3, 2), (5, 6, 7, 8), (1, 2, 6, 5), (3, 4, 8, 7), (2, 3, 7, 6), (1, 5, 8, 4)]
        for f in faces:
            self.lines.append("f " + " ".join(f"{base_v + i}/{base_t + k + 1}" for k, i in enumerate(f)))
        self.v += 8
        self.vt += 4

    def text(self):
        return "\n".join(self.lines) + "\n"


def box_sub():
    """A hull 1.5 wide and tall, 4.5 long, its bow open round a window the pilot looks out of; a conning
    tower with a hatch; two lamps; a screw."""
    w = ObjWriter("the box submarine")
    w.box("body", "body", -12, 0, -36, 12, 24, 30)              # the hull, to the bow's bulkhead
    w.box("body", "body", -12, 0, 30, 12, 10, 36)               # the bow under the window
    w.box("body", "body", -12, 22, 30, 12, 24, 36)              # over it
    w.box("body", "body", -12, 10, 30, -8, 22, 36)              # beside it, left
    w.box("body", "body", 8, 10, 30, 12, 22, 36)                # and right
    w.box("glass", "window", -8, 10, 35.5, 8, 22, 36)           # the bow window
    w.box("body", "body", -6, 24, -6, 6, 34, 10)                # the conning tower
    w.box("hatch", "hatch", -4, 34, -2, 4, 35, 6)               # its hatch
    w.box("lamp", "lamps", -10, 2, 36, -6, 6, 36.5)             # left lamp
    w.box("lamp", "lamps", 6, 2, 36, 10, 6, 36.5)               # right lamp
    w.box("trim", "fin", -1, 4, -40, 1, 22, -36)                # the rudder
    w.box("metal", "propeller", -1, 11, -39, 1, 13, -36)        # the shaft
    w.box("prop", "propeller", -8, 11, -38.5, 8, 13, -37.5)     # the blades, across
    w.box("prop", "propeller", -1, 4, -38.5, 1, 20, -37.5)      # and up and down
    return w.text()


BOX_SUB = {
    "mesh": f"{TEST}:box_sub",
    "texture": f"{TEST}:textures/entity/box_sub.png",
    "scale": 0.0625,
    "handedness": "right",
    "body": {"width": 1.5, "length": 4.5, "height": 1.5,
             "parts": [{"at": [0, 0, 26], "width": 1.5, "height": 1.5}, {"at": [0, 0, -26], "width": 1.5, "height": 1.5}]},
    "seats": [{"at": [0, 10, 31], "driver": True, "eye": [0, 16, 33]}, {"at": [0, 4, -4]}],
    "wheels": {"radius": 1, "drawn": False,
               "positions": [{"forward": 30, "right": -10}, {"forward": 30, "right": 10},
                             {"forward": -30, "right": -10}, {"forward": -30, "right": 10}]},
    "engine": {"max_speed": 0.3, "acceleration": 0.02, "reverse_speed": 0.1, "brake": 0.03},
    "climb": 0.5,
    "mass": 3.0,
    "fuel": {"capacity": 24000},
    "storage": {"chests": [{"at": [0, 2, -24], "yaw": 180, "scale": 0.3, "rows": 3}]},
    "headlights": {"at": [[-8, 4, 36.5], [8, 4, 36.5]], "part": {"material": "lamp"}, "range": 16},
    "paint": {"part": {"material": "body"}, "default": "yellow"},
    "glass": {"material": "glass"},
    "camera": 8.0,
}

BOX_SUB_DIVE = {
    "properties": {"engineSpeed": 0.018, "friction": 0.02, "verticalSpeed": 0.12, "yawSpeed": 2.5},
    "hull_drag": 0.04,
    "spool_ticks": 40,
    "rise": 0.06,
    "draft": 0.7,
    "tilt": 12,
    "hull": [{"from": [-12, 0, -36], "to": [12, 24, 36]},
             {"from": [-6, 24, -6], "to": [6, 34, 10]}],
    "propellers": [{"part": {"group": "propeller"}, "pivot": [0, 12, -38], "axis": [0, 0, 1], "speed": 1.0}],
    "upgrades": 4,
    "weapons": [[-6, 6, 38], [6, 6, 38]],
    "hatch": [0, 36, 2],
}


# ---------------------------------------------------------------- the items

def torpedo_tube_icon():
    """A steel tube seen end-on and along: a dark muzzle, two bands, a breech."""
    steel, dark, band, light = (128, 134, 142), (40, 42, 46), (176, 140, 60), (196, 202, 210)
    px = canvas(16, 16)
    noise = Noise(0x7B7B)
    for y in range(4, 12):
        for x in range(2, 14):
            px[y][x] = (*shade(steel, int((noise.next() - 0.5) * 14)), 255)
    for x in range(2, 14):
        px[4][x] = (*light, 255)
        px[11][x] = (*shade(steel, -40), 255)
    for y in range(4, 12):
        px[y][5] = (*band, 255)
        px[y][10] = (*band, 255)
    for y in range(5, 11):
        px[y][13] = (*dark, 255)
        px[y][14] = (*shade(steel, -20), 255)
    for y in range(6, 10):
        px[y][1] = (*shade(steel, -30), 255)
    return px


def torpedo_texture():
    """The torpedo's own 16 x 16: a grey body, a red warhead band, brass fins and screw."""
    grey, red, brass, dark = (150, 156, 164), (170, 40, 36), (186, 150, 70), (60, 62, 66)
    px = canvas(16, 16)
    noise = Noise(0x70F0)
    for y in range(16):
        for x in range(16):
            base = grey if y < 8 else red if y < 12 else brass if y < 15 else dark
            px[y][x] = (*shade(base, int((noise.next() - 0.5) * 12)), 255)
    return px


def torpedo_icon():
    """The torpedo for inventories, laid corner to corner: a grey body, a red warhead up-right, brass fins down-left."""
    grey, red, brass, dark = (150, 156, 164), (170, 40, 36), (186, 150, 70), (60, 62, 66)
    px = canvas(16, 16)
    for i in range(3, 13):
        for w in (-1, 0, 1):
            x, y = i + w, 15 - i
            if 0 <= x < 16 and 0 <= y < 16:
                px[y][x] = (*(red if i >= 11 else shade(grey, 20 if w < 0 else -25 if w > 0 else 0)), 255)
    px[2][13] = px[3][13] = (*shade(red, -30), 255)
    for (x, y) in ((2, 11), (2, 12), (3, 13), (4, 13), (1, 13), (2, 14)):
        px[y][x] = (*brass, 255)
    px[13][1] = (*dark, 255)
    return px


def cube(frm, to, u0, v0, u1, v1):
    face = {"uv": [u0, v0, u1, v1], "texture": "#all"}
    return {"from": frm, "to": to, "faces": {k: dict(face) for k in ("north", "south", "east", "west", "up", "down")}}


TORPEDO_MODEL = {
    "textures": {"all": "submersibles:item/torpedo", "particle": "submersibles:item/torpedo"},
    "elements": [
        cube([7, 7, 2], [9, 9, 13], 0, 0, 16, 8),          # the body, nose at +z
        cube([7.25, 7.25, 13], [8.75, 8.75, 14.5], 0, 8, 16, 12),   # the warhead
        cube([7.6, 7.6, 14.5], [8.4, 8.4, 15.2], 0, 8, 16, 12),     # its tip
        cube([5.5, 7.75, 2.5], [10.5, 8.25, 4], 0, 12, 16, 15),     # the fins, across
        cube([7.75, 5.5, 2.5], [8.25, 10.5, 4], 0, 12, 16, 15),     # and up and down
        cube([7.5, 7.5, 1], [8.5, 8.5, 2], 0, 15, 16, 16),          # the screw's hub
    ],
    "display": {
        "gui": {"rotation": [30, 225, 0], "translation": [0, 0, 0], "scale": [0.9, 0.9, 0.9]},
        "ground": {"rotation": [0, 0, 0], "translation": [0, 2, 0], "scale": [0.6, 0.6, 0.6]},
        "fixed": {"rotation": [0, 0, 0], "translation": [0, 0, 0], "scale": [1, 1, 1]},
        "thirdperson_righthand": {"rotation": [75, 45, 0], "translation": [0, 2.5, 0], "scale": [0.6, 0.6, 0.6]},
        "firstperson_righthand": {"rotation": [0, 45, 0], "translation": [0, 0, 0], "scale": [0.6, 0.6, 0.6]},
    },
}


# ---------------------------------------------------------------- the fit-out screen

PANEL = (198, 198, 198)
HI, LO, EDGE = (255, 255, 255), (85, 85, 85), (0, 0, 0)
SLOT_BG, SLOT_HI, SLOT_LO = (139, 139, 139), (255, 255, 255), (55, 55, 55)


def frame(px, x, y):
    """A vanilla-style slot: a sunken 18 x 18 square, its top-left at (x, y)."""
    for j in range(18):
        for i in range(18):
            c = SLOT_BG
            if i == 0 or j == 0:
                c = SLOT_LO
            elif i == 17 or j == 17:
                c = SLOT_HI
            px[y + j][x + i] = (*c, 255)


def fit_out_texture():
    px = canvas(256, 256)
    # The panel, vanilla's: a raised grey board with a dark rim and lit top-left edges.
    for y in range(178):
        for x in range(176):
            c = PANEL
            if x == 0 or y == 0 or x == 175 or y == 177:
                c = EDGE
            elif x <= 2 and y <= 175 or y <= 2 and x <= 173:
                c = HI
            elif x >= 173 or y >= 175:
                c = LO
            px[y][x] = (*c, 255)
    for row in range(3):
        for col in range(9):
            frame(px, 7 + col * 18, 95 + row * 18)
    for col in range(9):
        frame(px, 7 + col * 18, 153)
    frame(px, 176, 0)
    # The marks in the empty slots, faint: an upgrade's cog, a tube, a dye's drop.
    mark = (100, 100, 100, 150)
    cog = ["......XX......", "..X..XXXX..X..", ".XXXXXXXXXXXX.", "..XXX....XXX..", "..XX......XX..",
           "XXXX......XXXX", "XXXX......XXXX", "..XX......XX..", "..XXX....XXX..", ".XXXXXXXXXXXX.",
           "..X..XXXX..X..", "......XX......"]
    tube = ["..............", "XXXXXXXXXXXX..", "X..........XXX", "X..........X.X", "X..........X.X",
            "X..........XXX", "XXXXXXXXXXXX.."]
    drop = ["......X.......", ".....XXX......", "....XXXXX.....", "...XXXXXXX....", "..XXXXXXXXX...",
            "..XXXXXXXXX...", "..XXXXXXXXX...", "...XXXXXXX....", "....XXXXX....."]
    for shape, u in ((cog, 194), (tube, 210), (drop, 226)):
        top = (16 - len(shape)) // 2
        for j, line in enumerate(shape):
            for i, ch in enumerate(line):
                if ch == "X":
                    px[top + j][u + 1 + i] = mark
    return px


# ---------------------------------------------------------------- recipes, tags

def unlock(recipe: str, item: str) -> dict:
    return {
        "parent": "minecraft:recipes/root",
        "criteria": {
            "has_the_recipe": {"trigger": "minecraft:recipe_unlocked", "conditions": {"recipe": f"submersibles:{recipe}"}},
            f"has_{item.split(':')[1]}": {"trigger": "minecraft:inventory_changed", "conditions": {"items": [{"items": item}]}},
        },
        "requirements": [["has_the_recipe", f"has_{item.split(':')[1]}"]],
        "rewards": {"recipes": [f"submersibles:{recipe}"]},
    }


TORPEDO_TUBE_RECIPE = {
    "type": "minecraft:crafting_shaped",
    "category": "equipment",
    "pattern": ["III", "DRP", "III"],
    "key": {"I": {"tag": "c:ingots/iron"}, "D": {"item": "minecraft:dispenser"}, "R": {"tag": "c:dusts/redstone"},
            "P": {"item": "minecraft:piston"}},
    "result": {"id": "submersibles:torpedo_tube", "count": 1},
}

TORPEDO_RECIPE = {
    "type": "minecraft:crafting_shapeless",
    "category": "equipment",
    "ingredients": [{"item": "minecraft:tnt"}, {"tag": "c:ingots/iron"}, {"tag": "c:ingots/copper"}, {"tag": "c:gunpowders"}],
    "result": {"id": "submersibles:torpedo", "count": 2},
}

# Stand-ins for Immersive Aircraft's upgrades, on vanilla items, for the tests (which run without it):
# each the deltas of the upgrade it stands for, read by the same rule from the same directory.
TEST_UPGRADES = {
    "blaze_rod": {"engineSpeed": 0.4, "fuel": 0.3},        # a Nether Engine
    "iron_block": {"durability": 1.0},                     # a Hull Reinforcement
    "slime_ball": {"engineSpeed": -0.2, "fuel": -0.75},    # an Eco Engine
    "compass": {"wind": -1.0, "stabilizer": 0.03, "dials": -1.0},   # a Gyroscope with dials
}


def main() -> None:
    write_png(MAIN_ASSETS / "textures/item/torpedo_tube.png", 16, 16, torpedo_tube_icon())
    write_json(MAIN_ASSETS / "models/item/torpedo_tube.json", {"parent": "minecraft:item/generated", "textures": {"layer0": "submersibles:item/torpedo_tube"}})
    write_png(MAIN_ASSETS / "textures/item/torpedo.png", 16, 16, torpedo_texture())
    write_json(MAIN_ASSETS / "models/item/torpedo_3d.json", TORPEDO_MODEL)
    write_png(MAIN_ASSETS / "textures/item/torpedo_icon.png", 16, 16, torpedo_icon())
    # Its own flat icon in inventories and the hand's slot, the 3D torpedo everywhere else (NeoForge's per-view model).
    write_json(MAIN_ASSETS / "models/item/torpedo.json", {
        "loader": "neoforge:separate_transforms",
        "base": {"parent": "submersibles:item/torpedo_3d"},
        "perspectives": {"gui": {"parent": "minecraft:item/generated", "textures": {"layer0": "submersibles:item/torpedo_icon"}}},
    })
    write_png(MAIN_ASSETS / "textures/gui/fit_out.png", 256, 256, fit_out_texture())
    write_json(MAIN_DATA / "recipe/torpedo_tube.json", TORPEDO_TUBE_RECIPE)
    write_json(MAIN_DATA / "recipe/torpedo.json", TORPEDO_RECIPE)
    write_json(MAIN_DATA / "advancement/recipes/torpedo_tube.json", unlock("torpedo_tube", "minecraft:dispenser"))
    write_json(MAIN_DATA / "advancement/recipes/torpedo.json", unlock("torpedo", "submersibles:torpedo_tube"))
    write_json(MAIN_DATA / "tags/item/upgrades.json", {"values": [{"id": "#immersive_aircraft:upgrades", "required": False}]})
    write_json(MAIN_DATA / "tags/item/weapons.json", {"values": ["submersibles:torpedo_tube"]})
    write_json(MAIN_ASSETS / "sounds.json", SOUNDS_JSON)

    (TEST_ASSETS / "vanillawheels/mesh").mkdir(parents=True, exist_ok=True)
    (TEST_ASSETS / "vanillawheels/mesh/box_sub.obj").write_text(box_sub())
    write_png(TEST_ASSETS / "textures/entity/box_sub.png", 64, 64, atlas())
    write_json(TEST_ASSETS / "lang/en_us.json", {"vehicle.submersibles_gametest.box_sub": "Box Sub"})
    write_json(TEST_DATA / "vanillawheels/vehicle/box_sub.json", BOX_SUB)
    write_json(TEST_DATA / "submersibles/submarine/box_sub.json", BOX_SUB_DIVE)
    for item, deltas in TEST_UPGRADES.items():
        write_json(TEST_MINECRAFT / f"aircraft_upgrades/{item}.json", deltas)
    write_json(TEST_TAGS / "upgrades.json", {"values": [f"minecraft:{item}" for item in TEST_UPGRADES]})
    STRUCTURES.mkdir(parents=True, exist_ok=True)
    (STRUCTURES / "tank.snbt").write_text('{DataVersion: 3955, size: [48, 24, 24], data: [], entities: [], palette: [{Name: "minecraft:air"}]}\n')
    print("art written")


# ---------------------------------------------------------------- the sound

SOUND_SRC = ROOT / "devtools/art/sounds/src"

SOUNDS_JSON = {
    "torpedo_launch": {"sounds": [{"name": "submersibles:torpedo_launch", "attenuation_distance": 32}],
                       "subtitle": "subtitles.submersibles.torpedo_launch"},
}


def sounds() -> None:
    """The torpedo's launch: see devtools/art/sounds/SOURCES.md. Needs ffmpeg and numpy (`--with numpy`)."""
    import numpy as np
    sys.path.insert(0, str(ROOT.parent / "tools/sound"))
    import cutlib  # noqa: E402  (the shared cutter: minecraft mods/tools/sound)
    # One underwater whoosh from 0.3 s before its peak, so it starts hard and goes away: 15 ms in, 120 ms out.
    x = cutlib.cut(SOUND_SRC / "336469-underwater-torpedo-pass-bys.ogg", 13.28, 14.18)
    n_in, n_out = int(0.015 * cutlib.RATE), int(0.12 * cutlib.RATE)
    x[:n_in] *= np.linspace(0.0, 1.0, n_in)
    x[-n_out:] *= np.linspace(1.0, 0.0, n_out)
    cutlib.write_ogg(MAIN_ASSETS / "sounds/torpedo_launch.ogg", cutlib.normalize(x, 0.8))


if __name__ == "__main__":
    if sys.argv[1:] == ["sounds"]:
        sounds()
    else:
        main()
